refactor/bootstrap (#51)

diff --git a/vault/tooling/bootstrap b/vault/tooling/bootstrap
--- a/vault/tooling/bootstrap
+++ b/vault/tooling/bootstrap
@@ -2,17 +2,98 @@
 
 set -eu
 
+secrets_file="${1}"
+secret_files="${2}"
+
 # Add helm repository
-helm repo add hashicorp https://helm.releases.hashicorp.com
-helm repo update
+helm repo add hashicorp https://helm.releases.hashicorp.com && \
+  helm repo update
 
 kubectl create namespace vault || true
 
 # vault
 echo -e "\nDeploying vault..."
 vault_dir="$(dirname $0)/../vault"
+tooling_dir="$(dirname $0)"
 
 # Replace secrets
 sed -i "s|<path:secret/data/infra#domain>|${DOMAIN}|" "${vault_dir}"/values.yaml
+sed -i "s|<path:secret/data/infra#env>|${ENV}|" "${vault_dir}"/values.yaml
 
 kubectl kustomize "${vault_dir}" --enable-helm | kubectl apply -f -
+
+# Wait for vault pod to be created
+kubectl --namespace vault wait --for=create pod/vault-0 --timeout=60s
+
+# Wait for vault pod to init
+sleep 30
+
+kubectl --namespace vault exec vault-0 -- vault operator init -status > /dev/null || init_status=$?
+
+if [[ $init_status -eq 0 ]]; then
+  echo "Vault already initialized"
+fi
+
+if [[ $init_status -eq 1 ]]; then
+  echo "[!] Error checking vault init status"
+  exit 1
+fi
+
+if [[ $init_status -eq 2 ]]; then
+  echo "Initializing vault..."
+
+  initialize_output="$(kubectl --namespace vault exec vault-0 -- vault operator init)"
+
+  unseal_keys="$(echo "${initialize_output}" | grep "Unseal Key" | sed -r 's/^Unseal Key [1-5]\: (.*)$/\1/g')"
+  needed_unseal_keys="$(echo "${unseal_keys}" | head -n3)"
+
+  echo "Unseal keys:"
+  echo "${unseal_keys}"
+
+  count=1
+  while read key; do
+    kubectl --namespace vault exec vault-0 -- vault operator unseal "${key}"
+    KEY="key${count}" VALUE="${key}" yq -Yi '.vault.unsealer.[$ENV.KEY] = $ENV.VALUE' "${secrets_file}"
+    count=$((count + 1))
+  done <<< "${needed_unseal_keys}"
+
+  # Login
+  root_token="$(echo "${initialize_output}" | grep "Initial Root Token" | sed 's/ //g' | cut -d: -f2)"
+  kubectl --namespace vault exec vault-0 -- vault login "${root_token}" || exit 1
+fi
+
+# Enable auth engines
+kubectl --namespace vault exec vault-0 -- vault auth enable userpass || echo "Userpass auth already enabled"
+kubectl --namespace vault exec vault-0 -- vault auth enable kubernetes || echo "Kubernetes auth already enabled"
+
+# Create policies
+policies_dir="${tooling_dir}/policies"
+
+echo "Creating policies..."
+cat "${policies_dir}/admin.hcl" | kubectl --namespace vault exec -i vault-0 -- vault policy write admin -
+cat "${policies_dir}/read-only.hcl" | kubectl --namespace vault exec -i vault-0 -- vault policy write read-only -
+
+# Config Userpass auth for secrets loading
+echo "Configuring userpass auth..."
+kubectl --namespace vault exec vault-0 -- vault write auth/userpass/users/admin \
+  password="${VAULT_ADMIN_PASSWORD}" \
+  policies=admin
+
+# Config k8s auth for ArgoCD
+echo "Configuring k8s auth..."
+cluster_host="$(kubectl config view --minify --raw -o jsonpath='{.clusters[0].cluster.server}')"
+kubectl --namespace vault exec vault-0 -- vault write auth/kubernetes/config \
+  kubernetes_host="${cluster_host}"
+
+kubectl --namespace vault exec vault-0 -- vault write auth/kubernetes/role/argocd-reader \
+  bound_service_account_names=argocd-repo-server \
+  bound_service_account_namespaces=devops-tools \
+  policies=read-only \
+  ttl=24h
+
+# Enable kv2 engine
+kubectl --namespace vault exec vault-0 -- vault secrets enable -path=secret -version=2 kv || echo "Secrets path already enabled"
+
+echo "Loading secrets"
+"${tooling_dir}"/load-secrets "${secrets_file}"
+"${tooling_dir}"/load-secret-files "${secret_files}"
