ops: restore vpn

diff --git a/p2p/qbittorrent/templates/deployment.yaml b/p2p/qbittorrent/templates/deployment.yaml
--- a/p2p/qbittorrent/templates/deployment.yaml
+++ b/p2p/qbittorrent/templates/deployment.yaml
@@ -14,38 +14,38 @@ spec:
       labels:
         app: qbittorrent
     spec:
-      #initContainers:
-      #- name: vpn
-      #  image: {{ .Values.vpn.image.repository }}:{{ .Values.vpn.image.tag }}
-      #  restartPolicy: Always
-      #  securityContext:
-      #    capabilities:
-      #      add:
-      #      - NET_ADMIN
-      #  envFrom:
-      #  - secretRef:
-      #      name: qbittorrent-vpn-secret
-      #  env:
-      #  - name: VPN_SERVICE_PROVIDER
-      #    value: nordvpn
-      #  - name: VPN_TYPE
-      #    value: wireguard
-      #  - name: DNS_KEEP_NAMESERVER
-      #    value: "on"
-      #  - name: FIREWALL_OUTBOUND_SUBNETS
-      #    value: "10.42.0.0/15"
-      #- name: verify-vpn
-      #  image: busybox
-      #  command:
-      #  - sh
-      #  - -c
-      #  - |
-      #    sleep 30
-      #    while ! ping -c 1 8.8.8.8; do
-      #      echo "Ping failed, retrying in 5"
-      #      sleep 5
-      #    done
-      #    echo "ping succesfull, exiting"
+      initContainers:
+      - name: vpn
+        image: {{ .Values.vpn.image.repository }}:{{ .Values.vpn.image.tag }}
+        restartPolicy: Always
+        securityContext:
+          capabilities:
+            add:
+            - NET_ADMIN
+        envFrom:
+        - secretRef:
+            name: qbittorrent-vpn-secret
+        env:
+        - name: VPN_SERVICE_PROVIDER
+          value: nordvpn
+        - name: VPN_TYPE
+          value: wireguard
+        - name: DNS_KEEP_NAMESERVER
+          value: "on"
+        - name: FIREWALL_OUTBOUND_SUBNETS
+          value: "10.42.0.0/15"
+      - name: verify-vpn
+        image: busybox
+        command:
+        - sh
+        - -c
+        - |
+          sleep 30
+          while ! ping -c 1 8.8.8.8; do
+            echo "Ping failed, retrying in 5"
+            sleep 5
+          done
+          echo "ping succesfull, exiting"
       containers:
       - name: qbittorrent
         image: {{ .Values.qbittorrent.image.repository }}:{{ .Values.qbittorrent.image.tag }}
