chore: simplify bootstraping

diff --git a/devops-tools/argocd/values.yaml b/devops-tools/argocd/values.yaml
--- a/devops-tools/argocd/values.yaml
+++ b/devops-tools/argocd/values.yaml
@@ -20,23 +20,11 @@ configs:
           - |
             set -e
             echo "Replacing env vars in manifests"
-
-            if kubectl get cm homelab-vars -n argocd >/dev/null 2>&1; then
-              kubectl get cm homelab-vars -n argocd -o json |
-                jq -r '.data | to_entries[] | "\(.key)=\(.value)"' > /tmp/env
-              set -a
-              source /tmp/env
-              set +a
-            fi
-
-            # Render by type
-            if [[ -f Chart.yaml ]]; then
-              helm template . | envsubst '${INFRA_DOMAIN} ${INFRA_K8S_NFS} ${INFRA_DATA_NFS} ${INFRA_LB_IP}'
-            elif [[ -f kustomization.yaml ]]; then
+            if [[ -f kustomization.yaml ]]; then
               kustomize build . | envsubst '${INFRA_DOMAIN} ${INFRA_K8S_NFS} ${INFRA_DATA_NFS} ${INFRA_LB_IP}'
             else
-              find . -name '*.yaml' -print0 | \
-                xargs -0 cat | envsubst '${INFRA_DOMAIN} ${INFRA_K8S_NFS} ${INFRA_DATA_NFS} ${INFRA_LB_IP}'
+              echo "[!] Error during infra variables substitution"
+              exit 1
             fi
 
 dex:
