fix: clean stdout and use correct templating

diff --git a/devops-tools/argocd/values.yaml b/devops-tools/argocd/values.yaml
--- a/devops-tools/argocd/values.yaml
+++ b/devops-tools/argocd/values.yaml
@@ -19,11 +19,11 @@ configs:
           - "-c"
           - |
             set -e
-            echo "Replacing env vars in manifests"
+            echo "Replacing env vars in manifests" >&2
             if [[ -f kustomization.yaml ]]; then
               kustomize build . --enable-helm | envsubst '${INFRA_DOMAIN} ${INFRA_K8S_NFS} ${INFRA_DATA_NFS} ${INFRA_LB_IP}'
             else
-              echo "[!] Error during infra variables substitution"
+              echo "[!] Error during infra variables substitution" >&2
               exit 1
             fi
 
